server:
  port: 9005

spring:
  application:
    name: imes-warehouse
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.194.48:3306/jn-imes?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    #    password: 123456Zjx!
    password: 123456Zjx
    hikari:
      max-lifetime: 500000
  redis:
    host: 182.92.194.48
    port: 6379

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  rabbitmq:
    host: 182.92.194.48
    port: 5672
    virtual-host: /
    username: guest
    password: guest

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    cn.jianing.imes.warehouse.mapper: debug

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/