server:
  port: 6868

eureka:
  instance:
    hostname: eureka-server
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/  #eureka服务器地址
    fetch-registry: false     # 是否从Eureka服务器中拉取注册
    register-with-eureka: false     #是否注册到Eureka服务器中
spring:
  application:
    name: eureka-server