server:
  port: 9001

spring:
  application:
    name: imes-company
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.194.48:3306/jn-imes?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
#    password: 123456Zjx!
    password: 123456Zjx
  redis:
    host: 182.92.194.48
    port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    cn.jianing.imes.company.mapper: debug

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:6868/eureka/